[versions]
objectbox = "5.4.2"

# Android plugin 9 includes Kotlin 2.2.10
# https://developer.android.com/build/releases/agp-9-0-0-release-notes#runtime-dependency-on-kotlin-gradle-plugin
agp = "9.3.0"

activityKtx = "1.10.1"
appcompat = "1.7.1"
constraintlayout = "2.2.1"
material = "1.12.0"
lifecycleKtx = "2.9.2"
recyclerview = "1.4.0"
versions = "0.52.0" # https://github.com/ben-manes/gradle-versions-plugin/releases

[libraries]
objectbox-android = { module = "io.objectbox:objectbox-sync-android", version.ref = "objectbox" }
objectbox-kotlin = { module = "io.objectbox:objectbox-kotlin", version.ref = "objectbox" }
# ObjectBox with Admin web app for debugging
# https://docs.objectbox.io/data-browser
objectbox-android-admin = { module = "io.objectbox:objectbox-sync-android-objectbrowser", version.ref = "objectbox" }

androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleKtx" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleKtx" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-kapt = { id = "com.android.legacy-kapt", version.ref = "agp" }
# For ObjectBox: use the Sync variant of the plugin
objectbox = { id = "io.objectbox.sync", version.ref = "objectbox" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
