use_frameworks!

target 'client-swift-ios' do
  platform :ios, :deployment_target => '12.0'
  pod 'ObjectBox', '4.3.0-sync'
end

target 'client-swift-macos' do
  platform :osx, :deployment_target => '10.15'
  pod 'ObjectBox', '4.3.0-sync'
end
