# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# 1) Increase heap size to the value used in new Android project templates from the default 512 MB
# to avoid out of memory crashes when compiling Android projects.
# https://docs.gradle.org/current/userguide/config_gradle.html#sec:configuring_jvm_memory
# 2) To support Unicode characters in source code, set UTF-8 as the file encoding for the Gradle
# daemon, which will make most Java tools use it instead of the default system file encoding.
# https://docs.gradle.org/current/userguide/common_caching_problems.html#system_file_encoding
# Specifies the JVM arguments used for the daemon process.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
# org.gradle.parallel=true

# https://developer.android.com/jetpack/androidx/migrate
android.useAndroidX=true
