services:
  sync-server:
    image: objectboxio/sync-server-trial:latest
    platform: linux/amd64
    container_name: sync-server
    restart: always
    # Note: user and group ID 1000 may have to be adjusted to match your user IDs:
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "9980:9980"
      - "9999:9999"
    volumes:
      # Expose "current" (this) directory as "/data" in the container.
      - .:/data
    command: >
      --model ./objectbox-model.json
      --unsecured-no-authentication       
      --admin-bind 0.0.0.0:9980 
      --mongo-url mongodb+srv://user:password@solutionsassurance.n0kts.mongodb.net/?retryWrites=true&w=majority&appName=SolutionsAssurance
      --mongo-db objectbox_sync_test
      --debug

      
    

